sync_scenes:
apply_scene:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: light
          multiple: true
    scene:
      required: true
      example: Bright
      selector:
        select:
          custom_value: true
          options:
            - Bright
            - Cool bright
            - Dimmed
            - Read
            - Concentrate
            - Energise
            - Relax
            - Rest
            - Nightlight
health_fix:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          multiple: true
    action:
      default: resync
      selector:
        select:
          options:
            - refresh
            - resync
            - nudge
            - reconnect
notify:
  fields:
    kind:
      example: doorbell
      selector:
        text:
    people:
      example: Jamie
      selector:
        text:
          multiple: true
    title:
      selector:
        text:
    message:
      required: true
      selector:
        text:
          multiline: true
    admin_message:
      selector:
        text:
    tag:
      selector:
        text:
    link:
      example: /dashboard-mobile/todo
      selector:
        text:
    image:
      selector:
        text:
    critical:
      selector:
        boolean:
    data:
      selector:
        object:
