import { registerGaugeZoneCard } from './gauge-zone-card.js';
import { registerAlarmPanelCard } from './alarm-panel-card.js';
import { registerLightControlCard } from './light-control-card.js';
import { registerSceneStylesCard } from './scene-styles-card.js';
import { registerSceneBuilderCard } from './scene-builder-card.js';
import { registerSectionTitleCard } from './section-title-card.js';
import { registerSectionPanelCard } from './section-panel-card.js';
import { registerClimateCard } from './climate-card.js';
import { registerClimateZoneCard } from './climate-zone-card.js';
import { registerFanCard } from './fan-card.js';
import { registerAirPurifierCard } from './air-purifier-card.js';
import { registerCoAlarmCard } from './co-alarm-card.js';
import { registerCoverCard } from './cover-card.js';
import { registerDeviceHealthCard } from './device-health-card.js';
import { registerSecurityZoneCard } from './security-zone-card.js';
import { registerNavBarCard } from './nav-bar-card.js';
import { registerAutoLayoutCard } from './auto-layout-card.js';
import { registerHouseTasksCard } from './house-tasks-card.js';
import { registerEnergyCards } from './energy-cards.js';
import { registerTaskListCard } from './task-list-card.js';
import { registerNotificationsCard } from './notifications-card.js';
import { registerMediaCard } from './media-card.js';
import { registerSystemCard } from './system-card.js';
import { registerSafetyCard } from './safety-card.js';
import { registerPeopleCard } from './people-card.js';
import { registerCameraCard } from './camera-card.js';
import { registerPlacesCard } from './places-card.js';
import { registerCameraLinksCard } from './camera-links-card.js';
import { SUFFIX } from './suffix.js';

registerGaugeZoneCard();
registerAlarmPanelCard();
registerLightControlCard();
registerSceneStylesCard();
registerSceneBuilderCard();
registerSectionTitleCard();
registerSectionPanelCard();
registerClimateCard();
registerClimateZoneCard();
registerFanCard();
registerAirPurifierCard();
registerCoAlarmCard();
registerCoverCard();
registerDeviceHealthCard();
registerSecurityZoneCard();
registerNavBarCard();
registerAutoLayoutCard();
registerHouseTasksCard();
registerEnergyCards();
registerTaskListCard();
registerNotificationsCard();
registerMediaCard();
registerSystemCard();
registerSafetyCard();
registerPeopleCard();
registerCameraCard();
registerPlacesCard();
registerCameraLinksCard();

console.info(`%c CHURCH-DRIVE-CARDS${SUFFIX ? ' BETA' : ''} %c loaded `, 'color: white; background: #2196f3; font-weight: 700;', 'color: #2196f3; background: transparent;');
